triagem_task:
  description: |
    Para o caso '{case_id}', analise todos os documentos em '{documents}'.
    Use seu conhecimento de fundo do 'FAQ.pdf' para refinar sua análise.
    
    INSTRUÇÕES ESPECÍFICAS:
    1. Valide cada documento fornecido contra a lista de documentos OBRIGATÓRIOS
    2. Consulte SEMPRE o FAQ.pdf como fonte principal de regras, casos especiais e exceções
    3. VERIFIQUE SE TODOS os documentos obrigatórios estão presentes:
       - Contrato Social
       - Cartão CNPJ (se não estiver presente, identifique o CNPJ para geração automática)
       - Comprovante de endereço
       - Documentos dos sócios
    4. Se faltar Cartão CNPJ, IDENTIFIQUE o CNPJ da empresa no texto dos documentos
    5. QUANDO DETECTAR CNPJ SEM CARTÃO ATUALIZADO: Use a ferramenta 'enriquecer_cliente_api' 
       para gerar automaticamente o cartão CNPJ através da API da Receita Federal
    6. Use as ferramentas disponíveis para enriquecer dados quando necessário
    7. Determine o status geral do caso: 'Pendencia_Bloqueante', 'Pendencia_NaoBloqueante', ou 'Aprovado'
    8. Crie uma lista detalhada de ações requeridas para as pendências encontradas
    9. Classifique cada pendência como 'Bloqueante' ou 'NaoBloqueante'
    10. Para pendências de CNPJ, SEMPRE inclua o número do CNPJ extraído dos documentos
    
    CRITÉRIOS DE ANÁLISE:
    - Pendência Bloqueante: Impede a aprovação do cadastro (documentos obrigatórios ausentes, informações incorretas críticas)
    - Pendência Não-Bloqueante: Pode ser resolvida posteriormente (documentos complementares, pequenas correções)
    - Aprovado: Todos os requisitos essenciais atendidos
    
    Seu output final DEVE ser um único objeto JSON válido.
    NÃO inclua nenhum texto, explicação ou comentário fora do JSON. Apenas retorne o JSON puro, sem prefixos, sufixos ou mensagens adicionais. Todas as recomendações, observações e instruções devem estar dentro do objeto JSON.
    
    ATENÇÃO: Se você retornar qualquer texto fora do JSON, o sistema irá falhar. Apenas o JSON puro será aceito.
    
    Um único objeto JSON com a seguinte estrutura:
    {{
      "case_id": "{case_id}",
      "status_geral": "Pendencia_Bloqueante|Pendencia_NaoBloqueante|Aprovado",
      "resumo_analise": "Resumo executivo da análise realizada",
      "documentos_analisados": [
        {{
          "nome": "nome_do_documento.pdf",
          "status": "Conforme|Pendente|Ausente",
          "observacoes": "Detalhes específicos sobre o documento"
        }}
      ],
      "pendencias": [
        {{
          "tipo": "Bloqueante|NaoBloqueante",
          "categoria": "categoria_da_pendencia",
          "descricao": "Descrição detalhada da pendência",
          "acao_requerida": "Ação específica necessária para resolver",
          "prazo_sugerido": "Prazo recomendado para resolução"
        }}
      ],
      "proximos_passos": [
        "Lista de ações prioritárias para resolução das pendências"
      ],
      "recomendacoes": "Recomendações adicionais para o cliente",
      "data_analise": "{current_date}",
      "analista": "triagem_agent"
    }}
  expected_output: |
    Um único objeto JSON com a seguinte estrutura:
    {{
      "case_id": "{case_id}",
      "status_geral": "Pendencia_Bloqueante|Pendencia_NaoBloqueante|Aprovado",
      "resumo_analise": "Resumo executivo da análise realizada",
      "documentos_analisados": [
        {{
          "nome": "nome_do_documento.pdf",
          "status": "Conforme|Pendente|Ausente",
          "observacoes": "Detalhes específicos sobre o documento"
        }}
      ],
      "pendencias": [
        {{
          "tipo": "Bloqueante|NaoBloqueante",
          "categoria": "categoria_da_pendencia",
          "descricao": "Descrição detalhada da pendência",
          "acao_requerida": "Ação específica necessária para resolver",
          "prazo_sugerido": "Prazo recomendado para resolução"
        }}
      ],
      "proximos_passos": [
        "Lista de ações prioritárias para resolução das pendências"
      ],
      "recomendacoes": "Recomendações adicionais para o cliente",
      "data_analise": "{current_date}",
      "analista": "triagem_agent"
    }}
  agent: triagem_agent
  tools:
    - knowledge_base_query_tool
    - supabase_document_tool
    - enriquecer_cliente_api
  context: |
    Você está analisando documentos de cadastro para validação de conformidade.
    Use o FAQ.pdf como sua principal fonte de regras e exceções.
    Seja rigoroso mas justo na análise, considerando o contexto empresarial.
  output_format: "json" 